apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: notes-app
  labels:
    app: backend
spec:
  type: LoadBalancer  # This will create an AWS Classic Load Balancer automatically
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend
