apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: notes-app
  labels:
    app: frontend
spec:
  type: LoadBalancer  # This will create an AWS Classic Load Balancer automatically
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend
